title: "Light Pollution Docs"
baseurl: "/light-pollution"
url: "https://tallfurryman.github.io"

remote_theme: "academicpages/academicpages.github.io"

language_default: fr

collections_dir: "docs"
collections:
  en:
    output: true
    permalink: /:collection/:path/
    lang: en
  fr:
    output: true
    permalink: /:collection/:path/
    lang: fr

plugins:
  - jekyll-remote-theme

defaults:
  - scope:
      path: ""
    values:
      layout: single
      author_profile: false
  - scope:
      path: "en"
      type: en
    values:
      lang: en
      layout: single
  - scope:
      path: "fr"
      type: fr
    values:
      lang: fr
      layout: single
